[window]
opacity = 0.5
[font]
normal = { family = "JetBrainsMono Nerd Font", style = "Regular" }
size = 12.0


[cursor]
style = { shape = "Underline"}

[general]
import = ["~/.cache/wal/colors-alacritty.toml"]
